query-concurrency = 20
query-queue-size = 15
secret-store = "vault"
session-length = 120
http-bind-address = ":8086"
bolt-path = "/var/lib/influxdb2/influxd.bolt"
engine-path = "/var/lib/influxdb2/engine"
nats-port = "4222"